#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh --material&
killall mate-notification-daemon; dunst &
# wal -i /home/galocha/Imágenes/Wallpaper/wallpaper.jpg &

bspc config pointer_modifier mod1 # esto indica que la tecla windows es la tecla clave

bspc monitor -d I II III IV V  # si pones iconos en la polybar, esto cambia, si no se veran los numero romanos, numero, letras... lo que pongas

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
